/**
 * The globe's surface (globe plan 2026-09-26-0539 §7, M0-M3): the WGS84
 * ellipsoid generated by 3d-tiles-renderer's `GeneratedSurfacePlugin`,
 * textured from the COMMITTED Blue Marble pyramid (EPSG:4326, levels 0-5,
 * served locally: no network), each tile drawn with a lit copy of one
 * template material carrying the surface patch (night lights, water glint,
 * clouds), lit by the surface's own sun.
 *
 * @see globe-surface.ts.md
 */

import * as THREE from "three";
import { TilesRenderer } from "3d-tiles-renderer";
import { XYZTilesOverlay } from "3d-tiles-renderer/plugins";

import {
  GLOBE_SOURCES,
  globeSource,
  type GlobeSource,
  type GlobeSourceId,
} from "./globe-sources.js";
import { celestialToEcefQuaternion } from "./globe-stars.js";
import {
  applyGlobeSurface,
  createGlobeSurfaceUniforms,
  type GlobeSurfaceUniforms,
} from "./globe-surface-material.js";
import {
  GeneratedSurfacePlugin,
  type GeneratedSurfacePluginInstance,
} from "./vendor/generated-surface-plugin.js";

/** The surface's imagery, from the one registry (so it carries a credit). */
const IMAGERY = globeSource("blue-marble");

export const GLOBE_SURFACE = {
  /** The imagery's tiling: plate carrée, two tiles at level 0. */
  overlayProjection: IMAGERY.projection ?? "EPSG:4326",
  /** The committed levels (`scripts/fetch-globe-assets.mjs`). */
  levels: IMAGERY.levels ?? 1,
  /** The committed pyramid, served by the design system's routes. */
  imageryUrl: IMAGERY.path,
  /**
   * The tile cache's byte budget: about 90 resident level-3 tiles with mips
   * are ~31 MB (plan §7.4), so 64 MiB leaves room; the library unloads past
   * it. A parameter to measure on the phone, not a decision.
   */
  cacheBytes: 64 * 1024 * 1024,
  /**
   * The floor the library evicts down to (its default is 0.3 GB). It must
   * sit below the cap: the eviction pass trims towards the floor, so with
   * the floor above the cap a full cache shrinks only while other tiles are
   * pending, and once nothing is pending it stays over the cap
   * (LRUCache.unloadUnusedContent, 0.5.3). 48 MiB, plan §7.2.
   */
  cacheFloorBytes: 48 * 1024 * 1024,
  /**
   * The sun light's intensity: 5, the owner's look (round-4 plan
   * 2026-09-28-2105 DEC-GL4-1). Phase 1 lit the Earth at π (§7.3).
   */
  sunIntensity: 5,
} as const;

/** The renderer's runtime counters and cache size (not in its typings). */
interface TilesRuntime {
  readonly stats: {
    readonly queued: number;
    readonly downloading: number;
    readonly parsing: number;
    readonly loaded: number;
    /** Requests turned away because the cache was full. */
    readonly refused: number;
  };
  readonly lruCache: { readonly cachedBytes: number };
}

export interface GlobeSurfaceOptions {
  readonly overlayProjection: string;
  readonly levels: number;
  readonly applyOverlayTexture: boolean;
}

export interface GlobeSurface {
  readonly tiles: TilesRenderer;
  readonly group: THREE.Object3D;
  readonly plugin: GeneratedSurfacePluginInstance;
  readonly overlay: XYZTilesOverlay;
  readonly options: GlobeSurfaceOptions;
  /**
   * The sun: a directional light in `group`, intensity
   * `GLOBE_SURFACE.sunIntensity` (DEC-GL4-1), turned
   * with `tiles.group` so it stays the ECEF sun however the tiles are
   * placed.
   */
  readonly sun: THREE.DirectionalLight;
  /** The uniforms every tile's shader reads (the maps, the tuning). */
  readonly surfaceUniforms: GlobeSurfaceUniforms;
  /**
   * The patched material every tile's lit copy is made from, for another
   * carrier of the same surface (round-5 F1a: the relief's terrain tiles
   * wear the same look and read the same uniforms).
   */
  readonly template: THREE.MeshStandardMaterial;
  /**
   * Points the light AND the shader at the sun, a direction in ECEF (any
   * length). RangeError for a zero or non-finite vector.
   */
  setSun(directionEcef: THREE.Vector3): void;
  /** Per frame, before the render. */
  update(camera: THREE.Camera, renderer: THREE.WebGLRenderer): void;
  /**
   * Loaded models, the library's tile load errors, the cache's bytes, the
   * tiles still pending (queued, downloading or parsing), loaded, and
   * refused by a full cache (not pending: a starved cache would otherwise
   * read as settled), and the global maps loaded, failed, and in all.
   */
  state(): {
    models: number;
    tileErrors: number;
    cachedBytes: number;
    pendingTiles: number;
    loadedTiles: number;
    refusedTiles: number;
    mapsLoaded: number;
    mapErrors: number;
    mapsTotal: number;
  };
  /**
   * The rotation from the celestial frame (x to RA 0h, z to the pole) into
   * the WORLD at a Greenwich sidereal angle, turned exactly as the sun's
   * light is: the group's world rotation x the tile group's placement x
   * celestial-to-ECEF. The sky pass turns the stars by it.
   */
  celestialToWorld(
    siderealAngleRad: number,
    target?: THREE.Quaternion,
  ): THREE.Quaternion;
  /** The registry sources on screen, for the credits line. */
  activeSources(): GlobeSourceId[];
  dispose(): void;
}

/** Every mesh under `root`, with its material typed. */
function tileMeshes(
  root: THREE.Object3D,
): THREE.Mesh<THREE.BufferGeometry, THREE.Material>[] {
  const out: THREE.Mesh<THREE.BufferGeometry, THREE.Material>[] = [];
  root.traverse((node) => {
    // instanceof narrows to Mesh<any, any>: name the types.
    if (node instanceof THREE.Mesh) {
      out.push(node as THREE.Mesh<THREE.BufferGeometry, THREE.Material>);
    }
  });
  return out;
}

/**
 * Swap each mesh's unlit tile material for a lit copy of `template` that
 * keeps the mesh's own texture, and record the copy in `owned`. The
 * renderer still holds (and later frees) the original material; the texture
 * belongs to the overlay, which releases it itself.
 */
export function useLitMaterial(
  model: THREE.Object3D,
  template: THREE.MeshStandardMaterial,
  owned: WeakSet<THREE.Material>,
): void {
  for (const mesh of tileMeshes(model)) {
    const unlit = mesh.material as THREE.MeshBasicMaterial;
    const lit = template.clone();
    // Material.copy does not carry the compile hooks: the patch would be
    // lost without an error. Neither hook uses `this` (applyGlobeSurface
    // assigns arrow functions; three's defaults ignore it).
    // eslint-disable-next-line @typescript-eslint/unbound-method
    lit.onBeforeCompile = template.onBeforeCompile;
    // eslint-disable-next-line @typescript-eslint/unbound-method
    lit.customProgramCacheKey = template.customProgramCacheKey;
    lit.map = unlit.map ?? null;
    owned.add(lit);
    mesh.material = lit;
  }
}

/** Free the lit copies `useLitMaterial` made under `model`, not their maps. */
export function disposeLitMaterials(
  model: THREE.Object3D,
  owned: WeakSet<THREE.Material>,
): void {
  for (const mesh of tileMeshes(model)) {
    if (owned.has(mesh.material)) {
      owned.delete(mesh.material);
      mesh.material.dispose();
    }
  }
}

/** How the global maps are fetched: a texture that fills in later. */
export interface GlobeSurfaceLoader {
  loadTexture(
    source: GlobeSource,
    onLoad: () => void,
    onError: () => void,
  ): THREE.Texture;
}

const textureLoader: GlobeSurfaceLoader = {
  loadTexture: (source, onLoad, onError) =>
    new THREE.TextureLoader().load(
      source.path,
      () => onLoad(),
      undefined,
      () => onError(),
    ),
};

/**
 * One global map, configured from its registry entry: colour decoded from
 * sRGB, a mask read as numbers; wrapping in longitude, since the shader
 * samples across the 180° seam.
 */
function globalMap(
  source: GlobeSource,
  loader: GlobeSurfaceLoader,
  onLoad: () => void,
  onError: () => void,
): THREE.Texture {
  const texture = loader.loadTexture(source, onLoad, onError);
  texture.colorSpace =
    source.colorSpace === "srgb" ? THREE.SRGBColorSpace : THREE.NoColorSpace;
  texture.wrapS = THREE.RepeatWrapping;
  return texture;
}

/**
 * The globe's surface. The caller adds `group` to its scene, points the
 * sun with `setSun` and calls `update` every frame; `dispose` frees the
 * tiles, the template and the maps. `loader` fetches the global maps (a
 * TextureLoader by default; tests pass a stub).
 */
export function createGlobeSurface(
  loader: GlobeSurfaceLoader = textureLoader,
): GlobeSurface {
  const options: GlobeSurfaceOptions = {
    overlayProjection: GLOBE_SURFACE.overlayProjection,
    levels: GLOBE_SURFACE.levels,
    applyOverlayTexture: true,
  };
  const overlay = new XYZTilesOverlay({
    url: GLOBE_SURFACE.imageryUrl,
    projection: options.overlayProjection,
    levels: options.levels,
  });
  const plugin = new GeneratedSurfacePlugin({
    overlay,
    applyOverlayTexture: options.applyOverlayTexture,
  });
  const tiles = new TilesRenderer();
  tiles.registerPlugin(plugin);
  tiles.lruCache.maxBytesSize = GLOBE_SURFACE.cacheBytes;
  tiles.lruCache.minBytesSize = GLOBE_SURFACE.cacheFloorBytes;
  const runtime = tiles as unknown as TilesRuntime;
  let mapsLoaded = 0;
  let mapErrors = 0;
  const mapLoaded = () => {
    mapsLoaded += 1;
  };
  const mapError = () => {
    mapErrors += 1;
  };
  // The water mask is not among them: it is the imagery tiles' alpha.
  const maps = {
    night: globalMap(globeSource("black-marble"), loader, mapLoaded, mapError),
    clouds: globalMap(globeSource("clouds"), loader, mapLoaded, mapError),
  };
  const surfaceUniforms = createGlobeSurfaceUniforms(maps);
  const template = new THREE.MeshStandardMaterial({ roughness: 0.9 });
  applyGlobeSurface(template, surfaceUniforms);
  const sun = new THREE.DirectionalLight(0xffffff, GLOBE_SURFACE.sunIntensity);
  // NOT inside tiles.group: that group updates its children's world
  // matrices only when its own changes, so a light there keeps the matrix
  // it was made with, sits on its target and lights nothing (measured).
  const group = new THREE.Group();
  group.add(tiles.group, sun, sun.target);
  /**
   * The light shines from its position towards its target (the group's
   * origin): the ECEF sun turned by tiles.group's placement within the
   * group, identity in the lab, a rotation once phase 5 re-centres.
   */
  const syncSun = () => {
    sun.position
      .copy(surfaceUniforms.uSunEcef.value)
      .transformDirection(tiles.group.matrix);
    // The world-space sun for the cloud shading (review m4): the ECEF sun
    // through every group above the tiles, as the light ends up.
    tiles.group.updateWorldMatrix(true, false);
    surfaceUniforms.uSunWorld.value
      .copy(surfaceUniforms.uSunEcef.value)
      .transformDirection(tiles.group.matrixWorld);
  };
  const setSun = (direction: THREE.Vector3) => {
    const length = direction.length();
    if (!(length > 0 && Number.isFinite(length))) {
      throw new RangeError(
        `sun direction must be finite and non-zero, got ${direction.toArray().join(", ")}`,
      );
    }
    // The light shines from its position towards its target, the origin.
    surfaceUniforms.uSunEcef.value.copy(direction).divideScalar(length);
    syncSun();
  };
  setSun(surfaceUniforms.uSunEcef.value.clone());
  const owned = new WeakSet<THREE.Material>();
  let models = 0;
  let tileErrors = 0;
  tiles.addEventListener("load-model", ({ scene }) => {
    models += 1;
    useLitMaterial(scene, template, owned);
  });
  tiles.addEventListener("dispose-model", ({ scene }) => {
    disposeLitMaterials(scene, owned);
  });
  tiles.addEventListener("load-error", () => {
    tileErrors += 1;
  });
  let cameraSet: THREE.Camera | null = null;
  const resolution = new THREE.Vector2();
  return {
    tiles,
    group,
    plugin,
    overlay,
    options,
    sun,
    surfaceUniforms,
    template,
    setSun,
    update(camera, renderer) {
      if (cameraSet !== camera) {
        tiles.setCamera(camera);
        cameraSet = camera;
      }
      // DEVICE pixels: the library's setResolutionFromRenderer reads
      // getSize(), in CSS pixels, which at DPR 2 refines one level coarser
      // than the pyramid was sized for (plan §7.2).
      renderer.getDrawingBufferSize(resolution);
      tiles.setResolution(camera, resolution.x, resolution.y);
      camera.updateMatrixWorld();
      tiles.update();
      // A plugin may have moved the tiles this frame.
      syncSun();
    },
    state: () => {
      const { queued, downloading, parsing, loaded, refused } = runtime.stats;
      return {
        models,
        tileErrors,
        cachedBytes: runtime.lruCache.cachedBytes,
        pendingTiles: queued + downloading + parsing,
        loadedTiles: loaded,
        refusedTiles: refused,
        mapsLoaded,
        mapErrors,
        mapsTotal: Object.keys(maps).length,
      };
    },
    // Every registry source is drawn: the tiles (with the water mask in
    // their alpha), and the two maps.
    celestialToWorld(siderealAngleRad, target = new THREE.Quaternion()) {
      group.getWorldQuaternion(target);
      return target
        .multiply(tiles.group.quaternion)
        .multiply(celestialToEcefQuaternion(siderealAngleRad));
    },
    activeSources: () => GLOBE_SOURCES.map((s) => s.id),
    dispose() {
      tiles.dispose();
      template.dispose();
      for (const map of Object.values(maps)) map.dispose();
      sun.dispose();
    },
  };
}
