/**
 * The globe's surface (globe plan 2026-09-26-0539 §7, M0): the WGS84
 * ellipsoid generated by 3d-tiles-renderer's `GeneratedSurfacePlugin` from a
 * 4326 tiling, UNTEXTURED in M0 (the imagery arrives in M1, and no image is
 * requested until then), drawn with a lit material so the sun makes a day
 * and a night side.
 *
 * @see globe-surface.ts.md
 */

import * as THREE from "three";
import { TilesRenderer } from "3d-tiles-renderer";
import { XYZTilesOverlay } from "3d-tiles-renderer/plugins";

import {
  GeneratedSurfacePlugin,
  type GeneratedSurfacePluginInstance,
} from "./vendor/generated-surface-plugin.js";

export const GLOBE_SURFACE = {
  /** The tiling M1's imagery uses: plate carrée, two tiles at level 0. */
  overlayProjection: "EPSG:4326",
  /** Refinement levels of the generated geometry. */
  levels: 4,
  /** Where M1's imagery pyramid will live (nothing is fetched in M0). */
  imageryUrl: "/globe-assets/imagery/{z}/{x}/{y}.jpg",
  /** An ocean-like placeholder until the imagery arrives. */
  color: 0x3a6ea5,
} as const;

export interface GlobeSurfaceOptions {
  readonly overlayProjection: string;
  readonly levels: number;
  readonly applyOverlayTexture: boolean;
}

export interface GlobeSurface {
  readonly tiles: TilesRenderer;
  readonly group: THREE.Object3D;
  readonly plugin: GeneratedSurfacePluginInstance;
  readonly overlay: XYZTilesOverlay;
  readonly options: GlobeSurfaceOptions;
  /** Per frame, before the render. */
  update(camera: THREE.Camera, renderer: THREE.WebGLRenderer): void;
  /** Loaded models and the library's tile load errors. */
  state(): { models: number; tileErrors: number };
  dispose(): void;
}

/** Swap every mesh material under a loaded tile model for `material`. */
export function useLitMaterial(
  model: THREE.Object3D,
  material: THREE.Material,
): void {
  model.traverse((node) => {
    if (node instanceof THREE.Mesh) node.material = material;
  });
}

/**
 * The globe's surface. The caller adds `group` to its scene and calls
 * `update` every frame; `dispose` frees the tiles and the material.
 */
export function createGlobeSurface(): GlobeSurface {
  const options: GlobeSurfaceOptions = {
    overlayProjection: GLOBE_SURFACE.overlayProjection,
    levels: GLOBE_SURFACE.levels,
    applyOverlayTexture: false,
  };
  const overlay = new XYZTilesOverlay({
    url: GLOBE_SURFACE.imageryUrl,
    projection: options.overlayProjection,
    levels: options.levels,
  });
  const plugin = new GeneratedSurfacePlugin({
    overlay,
    applyOverlayTexture: options.applyOverlayTexture,
  });
  const tiles = new TilesRenderer();
  tiles.registerPlugin(plugin);
  const material = new THREE.MeshStandardMaterial({
    color: GLOBE_SURFACE.color,
    roughness: 0.9,
  });
  let models = 0;
  let tileErrors = 0;
  tiles.addEventListener("load-model", ({ scene }) => {
    models += 1;
    useLitMaterial(scene, material);
  });
  tiles.addEventListener("load-error", () => {
    tileErrors += 1;
  });
  let cameraSet: THREE.Camera | null = null;
  return {
    tiles,
    group: tiles.group,
    plugin,
    overlay,
    options,
    update(camera, renderer) {
      if (cameraSet !== camera) {
        tiles.setCamera(camera);
        cameraSet = camera;
      }
      tiles.setResolutionFromRenderer(camera, renderer);
      camera.updateMatrixWorld();
      tiles.update();
    },
    state: () => ({ models, tileErrors }),
    dispose() {
      tiles.dispose();
      material.dispose();
    },
  };
}
