/**
 * The globe's surface (globe plan 2026-09-26-0539 §7, M0-M3): the WGS84
 * ellipsoid generated by 3d-tiles-renderer's `GeneratedSurfacePlugin`,
 * textured from the COMMITTED Blue Marble pyramid (EPSG:4326, levels 0-5,
 * served locally: no network), each tile drawn with a lit copy of one
 * template material carrying the surface patch (night lights, water glint,
 * clouds), lit by the surface's own sun.
 *
 * @see globe-surface.ts.md
 */

import * as THREE from "three";
import { TilesRenderer } from "3d-tiles-renderer";
import { XYZTilesOverlay } from "3d-tiles-renderer/plugins";

import {
  GLOBE_SOURCES,
  globeSource,
  type GlobeSource,
  type GlobeSourceId,
} from "./globe-sources.js";
import {
  type GlobeCloudShell,
  createGlobeCloudShell,
} from "./globe-cloud-shell.js";
import { celestialToEcefQuaternion } from "./globe-stars.js";
import { topLevelReady } from "./globe-band-gate.js";
import { createMaterialRetirer } from "./globe-warm-material.js";
import {
  applyGlobeSurface,
  createGlobeSurfaceUniforms,
  type GlobeSurfacePatchOptions,
  type GlobeSurfaceUniforms,
} from "./globe-surface-material.js";
import {
  GeneratedSurfacePlugin,
  type GeneratedSurfacePluginInstance,
} from "./vendor/generated-surface-plugin.js";
import { globeMapLoader, type GlobeSurfaceLoader } from "./globe-map-loader.js";

/** The surface's imagery, from the one registry (so it carries a credit). */
const IMAGERY = globeSource("blue-marble");

export const GLOBE_SURFACE = {
  /**
   * The first look's sphere, as a share of the ellipsoid's radii: 6 km
   * under it, so the tiles cover it wherever they are drawn (DEC-FR2-6).
   */
  firstLookDepth: 0.999,
  /**
   * The first look ends for good once the camera goes below this, m: the
   * band and the relief take the pixels there, and kept on it drew a whole
   * sphere under the relief every frame (DEC-FR2-6).
   */
  firstLookFloorM: 2_000_000,
  /** The imagery's tiling: plate carrée, two tiles at level 0. */
  overlayProjection: IMAGERY.projection ?? "EPSG:4326",
  /** The committed levels (`scripts/fetch-globe-assets.mjs`). */
  levels: IMAGERY.levels ?? 1,
  /** The committed pyramid, served by the design system's routes. */
  imageryUrl: IMAGERY.path,
  /**
   * The tile cache's byte budget: about 90 resident level-3 tiles with mips
   * are ~31 MB (plan §7.4), so 64 MiB leaves room; the library unloads past
   * it. A parameter to measure on the phone, not a decision.
   */
  cacheBytes: 64 * 1024 * 1024,
  /**
   * The floor the library evicts down to (its default is 0.3 GB). It must
   * sit below the cap: the eviction pass trims towards the floor, so with
   * the floor above the cap a full cache shrinks only while other tiles are
   * pending, and once nothing is pending it stays over the cap
   * (LRUCache.unloadUnusedContent, 0.5.3). 48 MiB, plan §7.2.
   */
  cacheFloorBytes: 48 * 1024 * 1024,
  /**
   * The sun light's intensity: 5, the owner's look (round-4 plan
   * 2026-09-28-2105 DEC-GL4-1). Phase 1 lit the Earth at π (§7.3).
   */
  sunIntensity: 5,
} as const;

/** The renderer's runtime counters and cache size (not in its typings). */
interface TilesRuntime {
  readonly stats: {
    readonly queued: number;
    readonly downloading: number;
    readonly parsing: number;
    readonly loaded: number;
    /** Requests turned away because the cache was full. */
    readonly refused: number;
  };
  readonly lruCache: { readonly cachedBytes: number };
  /** The tile tree and the update count, for `topLevelReady`. */
  readonly root: unknown;
  readonly frameCount: number;
}

export interface GlobeSurfaceOptions {
  readonly overlayProjection: string;
  readonly levels: number;
  readonly applyOverlayTexture: boolean;
}

export interface GlobeSurface {
  readonly tiles: TilesRenderer;
  readonly group: THREE.Object3D;
  readonly plugin: GeneratedSurfacePluginInstance;
  readonly overlay: XYZTilesOverlay;
  readonly options: GlobeSurfaceOptions;
  /**
   * The sun: a directional light in `group`, intensity
   * `GLOBE_SURFACE.sunIntensity` (DEC-GL4-1), turned
   * with `tiles.group` so it stays the ECEF sun however the tiles are
   * placed.
   */
  readonly sun: THREE.DirectionalLight;
  /** The uniforms every tile's shader reads (the maps, the tuning). */
  readonly surfaceUniforms: GlobeSurfaceUniforms;
  /**
   * The patched material every tile's lit copy is made from, for another
   * carrier of the same surface (round-5 F1a: the relief's terrain tiles
   * wear the same look and read the same uniforms).
   */
  readonly template: THREE.MeshStandardMaterial;
  /**
   * Points the light AND the shader at the sun, a direction in ECEF (any
   * length). RangeError for a zero or non-finite vector.
   */
  setSun(directionEcef: THREE.Vector3): void;
  /** Per frame, before the render. */
  update(camera: THREE.Camera, renderer: THREE.WebGLRenderer): void;
  /**
   * Loaded models, the library's tile load errors, the cache's bytes, the
   * tiles still pending (queued, downloading or parsing), loaded, and
   * refused by a full cache (not pending: a starved cache would otherwise
   * read as settled), and the global maps loaded, failed, and in all.
   */
  state(): {
    models: number;
    tileErrors: number;
    cachedBytes: number;
    pendingTiles: number;
    loadedTiles: number;
    refusedTiles: number;
    mapsLoaded: number;
    mapErrors: number;
    mapsTotal: number;
    /** Whether the first look (the imagery's level 0) is in (DEC-FR2-6). */
    firstLookReady: boolean;
  };
  /**
   * The rotation from the celestial frame (x to RA 0h, z to the pole) into
   * the WORLD at a Greenwich sidereal angle, turned exactly as the sun's
   * light is: the group's world rotation x the tile group's placement x
   * celestial-to-ECEF. The sky pass turns the stars by it.
   */
  celestialToWorld(
    siderealAngleRad: number,
    target?: THREE.Quaternion,
  ): THREE.Quaternion;
  /**
   * The clouds' own shell above the ground (`globe-cloud-shell.ts`, round-6
   * plan G6-2), in the tiles' ECEF frame; hidden until
   * `setCloudShellShare` gives it a share.
   */
  readonly cloudShell: GlobeCloudShell;
  /**
   * The globe's first look (round-2 plan DEC-FR2-6): a sphere a fraction
   * under the ellipsoid, in the tiles' frame, in the surface's own material
   * without a map (so it shows the imagery's level 0, lit and clouded as
   * the tiles are), drawn until the globe can draw its whole view. The tile
   * renderer draws a tile only once its imagery is in: before that there was
   * no sphere at all, only the atmosphere's veil over black.
   */
  readonly firstLook: THREE.Mesh;
  /**
   * How much of the clouds the shell draws (0-1); the surface paints the
   * rest into the ground's colour. 0, the default, is the look before.
   * `flat` (0-1, default 1) fades both forms and the water's cloud mask
   * by the flat layer's share by altitude (round-2 plan DEC-FR2-5). RangeError
   * outside 0-1.
   */
  setCloudShellShare(share: number, flat?: number): void;
  /** The registry sources on screen, for the credits line. */
  activeSources(): GlobeSourceId[];
  dispose(): void;
}

/**
 * Every mesh under `root`, with its material typed (shared with the relief
 * carrier, `globe-terrain.ts`).
 */
export function tileMeshes(
  root: THREE.Object3D,
): THREE.Mesh<THREE.BufferGeometry, THREE.Material>[] {
  const out: THREE.Mesh<THREE.BufferGeometry, THREE.Material>[] = [];
  root.traverse((node) => {
    // instanceof narrows to Mesh<any, any>: name the types.
    if (node instanceof THREE.Mesh) {
      out.push(node as THREE.Mesh<THREE.BufferGeometry, THREE.Material>);
    }
  });
  return out;
}

/**
 * Swap each mesh's unlit tile material for a lit copy of `template` that
 * keeps the mesh's own texture, and record the copy in `owned`. The
 * renderer still holds (and later frees) the original material; the texture
 * belongs to the overlay, which releases it itself.
 */
export function useLitMaterial(
  model: THREE.Object3D,
  template: THREE.MeshStandardMaterial,
  owned: WeakSet<THREE.Material>,
): void {
  for (const mesh of tileMeshes(model)) {
    const unlit = mesh.material as THREE.MeshBasicMaterial;
    const lit = litCopy(template);
    lit.map = unlit.map ?? null;
    owned.add(lit);
    mesh.material = lit;
  }
}

/**
 * A clone of the patched `template` that keeps its compile hooks and
 * program key: Material.copy does not carry them, and the patch would be
 * lost without an error. Neither hook uses `this` (applyGlobeSurface
 * assigns arrow functions; three's defaults ignore it). Shared with the
 * relief carrier (`globe-terrain.ts`).
 */
export function litCopy(
  template: THREE.MeshStandardMaterial,
): THREE.MeshStandardMaterial {
  const lit = template.clone();
  // eslint-disable-next-line @typescript-eslint/unbound-method
  lit.onBeforeCompile = template.onBeforeCompile;
  // eslint-disable-next-line @typescript-eslint/unbound-method
  lit.customProgramCacheKey = template.customProgramCacheKey;
  return lit;
}

/** Free the lit copies `useLitMaterial` made under `model`, not their maps. */
export function disposeLitMaterials(
  model: THREE.Object3D,
  owned: WeakSet<THREE.Material>,
  retire: (material: THREE.Material) => void = (m) => m.dispose(),
): void {
  for (const mesh of tileMeshes(model)) {
    if (owned.has(mesh.material)) {
      owned.delete(mesh.material);
      retire(mesh.material);
    }
  }
}

export type { GlobeSurfaceLoader } from "./globe-map-loader.js";
/** The plain image-element loader, for a page that compares the two paths. */
export { elementMapLoader } from "./globe-map-loader.js";

/**
 * One global map, configured from its registry entry: colour decoded from
 * sRGB, a mask read as numbers, a grey map as one channel; wrapping in
 * longitude, since the shader samples across the 180° seam.
 */
function globalMap(
  source: GlobeSource,
  loader: GlobeSurfaceLoader,
  onLoad: () => void,
  onError: () => void,
): THREE.Texture {
  const texture = loader.loadTexture(source, onLoad, onError);
  texture.colorSpace =
    source.colorSpace === "srgb" ? THREE.SRGBColorSpace : THREE.NoColorSpace;
  if (source.grey) texture.format = THREE.RedFormat;
  texture.wrapS = THREE.RepeatWrapping;
  return texture;
}

/**
 * The first look's next state (round-2 plan DEC-FR2-6): done for good once
 * the globe has drawn its whole view (`drawn`) or the camera has gone below
 * `firstLookFloorM`, shown while its images are in (`imagesIn`) and it is
 * not done. Shown again whenever the globe could
 * not draw its view (zooming out of the band), it filled the very holes the
 * handover's positive control must see: it is for the start only. An
 * altitude not known (not a positive number: a camera still at the Earth's
 * centre reads 0) decides nothing.
 */
export function firstLookStep(
  done: boolean,
  imagesIn: boolean,
  drawn: boolean,
  altitudeM: number,
): { readonly done: boolean; readonly shown: boolean } {
  const low = altitudeM > 0 && altitudeM < GLOBE_SURFACE.firstLookFloorM;
  const next = done || drawn || low;
  return { done: next, shown: imagesIn && !next };
}

/**
 * A new overlay of the globe's imagery (the committed Blue Marble pyramid:
 * `GLOBE_SURFACE.imageryUrl`, its projection and levels). Each carrier that
 * draws it gets its own: an overlay's image cache is shared by every plugin
 * that uses it, so releasing one carrier's tiles freed imagery the other was
 * still composing (review 2026-10-03-1835 major 4 with the band's release).
 */
export function createGlobeImagery(): XYZTilesOverlay {
  return new XYZTilesOverlay({
    url: GLOBE_SURFACE.imageryUrl,
    projection: GLOBE_SURFACE.overlayProjection,
    levels: GLOBE_SURFACE.levels,
  });
}

/**
 * The globe's surface. The caller adds `group` to its scene, points the
 * sun with `setSun` and calls `update` every frame; `dispose` frees the
 * tiles, the template and the maps. `loader` fetches the global maps
 * (`globeMapLoader()` by default: off the main thread where the browser
 * can; tests pass a stub).
 */
export function createGlobeSurface(
  loader: GlobeSurfaceLoader = globeMapLoader(),
  patch: GlobeSurfacePatchOptions = {},
): GlobeSurface {
  const options: GlobeSurfaceOptions = {
    overlayProjection: GLOBE_SURFACE.overlayProjection,
    levels: GLOBE_SURFACE.levels,
    applyOverlayTexture: true,
  };
  const overlay = createGlobeImagery();
  const plugin = new GeneratedSurfacePlugin({
    overlay,
    applyOverlayTexture: options.applyOverlayTexture,
  });
  const tiles = new TilesRenderer();
  tiles.registerPlugin(plugin);
  tiles.lruCache.maxBytesSize = GLOBE_SURFACE.cacheBytes;
  tiles.lruCache.minBytesSize = GLOBE_SURFACE.cacheFloorBytes;
  const runtime = tiles as unknown as TilesRuntime;
  let mapsLoaded = 0;
  let mapErrors = 0;
  const mapLoaded = () => {
    mapsLoaded += 1;
  };
  const mapError = () => {
    mapErrors += 1;
  };
  // The first look waits for the cloud map as well as its two halves, so
  // it shows the Earth as the tiles will, clouds included (round-3 plan M1:
  // the 4,096 map arrives after the halves); a failed map holds nothing.
  let cloudsSettled = false;
  const cloudsIn = () => {
    cloudsSettled = true;
  };
  // The water mask is not among them: it is the imagery tiles' alpha.
  const maps = {
    night: globalMap(globeSource("black-marble"), loader, mapLoaded, mapError),
    clouds: globalMap(
      globeSource("clouds"),
      loader,
      () => {
        mapLoaded();
        cloudsIn();
      },
      () => {
        mapError();
        cloudsIn();
      },
    ),
  };
  // The first look (round-2 plan 2026-10-07-2350 DEC-FR2-6): the imagery
  // pyramid's level 0, the whole Earth in two tiles, loaded with the global
  // maps, long before the tile renderer asks for its first tiles, and drawn
  // on a sphere of its own (`firstLook`): the renderer draws a tile only
  // once its imagery is in, so until then there was only the atmosphere's
  // veil over black (measured: 7 s of one blue in a smoke). Not counted with
  // the global maps: the loading label is about those; a failure keeps the
  // plain look.
  const imagery = globeSource("blue-marble");
  let firstLookIn = 0;
  const firstLookImagesIn = () =>
    surfaceUniforms.uDayReady.value === 1 && cloudsSettled;
  const firstLookHalf = (x: number) => {
    const texture = loader.loadTexture(
      {
        ...imagery,
        path: imagery.path
          .replace("{z}", "0")
          .replace("{x}", String(x))
          .replace("{y}", "0"),
      },
      () => {
        firstLookIn += 1;
        if (firstLookIn === 2) surfaceUniforms.uDayReady.value = 1;
      },
      () => {},
    );
    texture.colorSpace = THREE.SRGBColorSpace;
    return texture;
  };
  const surfaceUniforms = createGlobeSurfaceUniforms({
    ...maps,
    dayWest: firstLookHalf(0),
    dayEast: firstLookHalf(1),
  });
  const template = new THREE.MeshStandardMaterial({ roughness: 0.9 });
  applyGlobeSurface(template, surfaceUniforms, patch);
  const sun = new THREE.DirectionalLight(0xffffff, GLOBE_SURFACE.sunIntensity);
  // NOT inside tiles.group: that group updates its children's world
  // matrices only when its own changes, so a light there keeps the matrix
  // it was made with, sits on its target and lights nothing (measured).
  const group = new THREE.Group();
  group.add(tiles.group, sun, sun.target);
  // The cloud shell in the tiles' frame: a holder that copies their
  // placement (not inside tiles.group, whose children keep stale world
  // matrices, as the light's comment says).
  const cloudShell = createGlobeCloudShell({
    uniforms: surfaceUniforms,
    radii: [
      tiles.ellipsoid.radius.x,
      tiles.ellipsoid.radius.y,
      tiles.ellipsoid.radius.z,
    ],
  });
  const cloudFrame = new THREE.Group();
  cloudFrame.matrixAutoUpdate = false;
  cloudFrame.add(cloudShell.mesh);
  const firstLook = new THREE.Mesh(
    new THREE.SphereGeometry(1, 96, 48),
    litCopy(template),
  );
  // The sphere's poles on the ECEF z axis (three's sphere has them on y).
  firstLook.geometry.rotateX(Math.PI / 2);
  firstLook.scale
    .set(
      tiles.ellipsoid.radius.x,
      tiles.ellipsoid.radius.y,
      tiles.ellipsoid.radius.z,
    )
    .multiplyScalar(GLOBE_SURFACE.firstLookDepth);
  // Hidden until an update decides: a page that never calls it (the terrain
  // lab) drew it under its relief.
  firstLook.visible = false;
  cloudFrame.add(firstLook);
  let firstLookDone = false;
  const cameraEcef = new THREE.Vector3();
  group.add(cloudFrame);
  /**
   * The light shines from its position towards its target (the group's
   * origin): the ECEF sun turned by tiles.group's placement within the
   * group, identity in the lab, a rotation once phase 5 re-centres.
   */
  const syncSun = () => {
    // The sky fill's light, by role: this light's colour times intensity.
    surfaceUniforms.uSunRadiance.value
      .set(sun.color.r, sun.color.g, sun.color.b)
      .multiplyScalar(sun.intensity);
    sun.position
      .copy(surfaceUniforms.uSunEcef.value)
      .transformDirection(tiles.group.matrix);
    cloudFrame.matrix.copy(tiles.group.matrix);
    cloudFrame.matrixWorldNeedsUpdate = true;
    // The world-space sun for the cloud shading (review m4): the ECEF sun
    // through every group above the tiles, as the light ends up.
    tiles.group.updateWorldMatrix(true, false);
    surfaceUniforms.uSunWorld.value
      .copy(surfaceUniforms.uSunEcef.value)
      .transformDirection(tiles.group.matrixWorld);
  };
  const setSun = (direction: THREE.Vector3) => {
    const length = direction.length();
    if (!(length > 0 && Number.isFinite(length))) {
      throw new RangeError(
        `sun direction must be finite and non-zero, got ${direction.toArray().join(", ")}`,
      );
    }
    // The light shines from its position towards its target, the origin.
    surfaceUniforms.uSunEcef.value.copy(direction).divideScalar(length);
    syncSun();
  };
  setSun(surfaceUniforms.uSunEcef.value.clone());
  const owned = new WeakSet<THREE.Material>();
  // The last retired lit copy stays alive, so the globe's program survives
  // a release of every tile (globe-warm-material.ts).
  const retirer = createMaterialRetirer();
  let models = 0;
  let tileErrors = 0;
  tiles.addEventListener("load-model", ({ scene }) => {
    models += 1;
    useLitMaterial(scene, template, owned);
  });
  tiles.addEventListener("dispose-model", ({ scene }) => {
    disposeLitMaterials(scene, owned, (m) => retirer.retire(m));
  });
  tiles.addEventListener("load-error", () => {
    tileErrors += 1;
  });
  let cameraSet: THREE.Camera | null = null;
  const resolution = new THREE.Vector2();
  return {
    tiles,
    group,
    plugin,
    overlay,
    options,
    sun,
    surfaceUniforms,
    template,
    setSun,
    update(camera, renderer) {
      if (cameraSet !== camera) {
        tiles.setCamera(camera);
        cameraSet = camera;
      }
      // DEVICE pixels: the library's setResolutionFromRenderer reads
      // getSize(), in CSS pixels, which at DPR 2 refines one level coarser
      // than the pyramid was sized for (plan §7.2).
      renderer.getDrawingBufferSize(resolution);
      tiles.setResolution(camera, resolution.x, resolution.y);
      camera.updateMatrixWorld();
      tiles.update();
      // The first look once its images are in (before, a plain white ball),
      // until the globe has first drawn its whole view.
      const look = firstLookStep(
        firstLookDone,
        firstLookImagesIn(),
        topLevelReady(runtime),
        tiles.ellipsoid.getPositionElevation(
          tiles.group.worldToLocal(cameraEcef.copy(camera.position)),
        ),
      );
      firstLookDone = look.done;
      firstLook.visible = look.shown;
      // A plugin may have moved the tiles this frame.
      syncSun();
    },
    state: () => {
      const { queued, downloading, parsing, loaded, refused } = runtime.stats;
      return {
        models,
        tileErrors,
        cachedBytes: runtime.lruCache.cachedBytes,
        pendingTiles: queued + downloading + parsing,
        loadedTiles: loaded,
        refusedTiles: refused,
        mapsLoaded,
        mapErrors,
        mapsTotal: Object.keys(maps).length,
        firstLookReady: firstLookImagesIn(),
      };
    },
    // Every registry source is drawn: the tiles (with the water mask in
    // their alpha), and the two maps.
    celestialToWorld(siderealAngleRad, target = new THREE.Quaternion()) {
      group.getWorldQuaternion(target);
      return target
        .multiply(tiles.group.quaternion)
        .multiply(celestialToEcefQuaternion(siderealAngleRad));
    },
    activeSources: () => GLOBE_SOURCES.map((s) => s.id),
    cloudShell,
    firstLook,
    setCloudShellShare(share, flat = 1) {
      for (const [name, v] of [
        ["share", share],
        ["flat share", flat],
      ] as const) {
        if (!(v >= 0 && v <= 1)) {
          throw new RangeError(`the ${name} must be in [0, 1], got ${v}`);
        }
      }
      cloudShell.setShare(share * flat);
      surfaceUniforms.uCloudInSurface.value = (1 - share) * flat;
      surfaceUniforms.uCloudFlat.value = flat;
    },
    dispose() {
      cloudShell.dispose();
      firstLook.geometry.dispose();
      (firstLook.material as THREE.Material).dispose();
      tiles.dispose();
      retirer.dispose();
      template.dispose();
      for (const map of Object.values(maps)) map.dispose();
      surfaceUniforms.uDayWest.value.dispose();
      surfaceUniforms.uDayEast.value.dispose();
      sun.dispose();
    },
  };
}
