import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import {
  BlobReader,
  TextWriter,
  Uint8ArrayWriter,
  ZipReader,
} from "@zip.js/zip.js";
import { describe, expect, it } from "vitest";

import { parseTourManifest } from "gps-plus-slam-app-framework/ar/tour-manifest";
import {
  checkGlbInert,
  checkImageWithinCap,
  tourMediaTypeOfEntry,
} from "gps-plus-slam-app-framework/ar/tour-media";

// Why these tests matter: the sample tour (owner decision S-D9) is the
// owner's first phone test of stations before in-app authoring exists. It is
// generated by scripts/build-sample-tour.mjs and committed under public/, so
// nothing else checks it: a broken asset or an invalid tour.json would only
// show on the phone, at Marienplatz or after a relocation. These tests read
// the committed file through the same parsers and checks the viewer uses.

const ZIP = fileURLToPath(
  new URL("../public/samples/marienplatz-tour.zip", import.meta.url),
);

async function entries(): Promise<Map<string, Uint8Array>> {
  const reader = new ZipReader(new BlobReader(new Blob([readFileSync(ZIP)])));
  const out = new Map<string, Uint8Array>();
  for (const entry of await reader.getEntries()) {
    if (entry.directory || entry.getData === undefined) continue;
    out.set(entry.filename, await entry.getData(new Uint8ArrayWriter()));
  }
  await reader.close();
  return out;
}

const M_PER_DEG = 111_320;
function metres(
  a: { lat: number; lon: number },
  b: { lat: number; lon: number },
): number {
  const cos = Math.cos(((a.lat + b.lat) / 2) * (Math.PI / 180));
  return Math.hypot(
    (b.lat - a.lat) * M_PER_DEG,
    (b.lon - a.lon) * M_PER_DEG * cos,
  );
}

describe("the sample tour (public/samples/marienplatz-tour.zip)", () => {
  it("is a valid version 2 tour with three geo stations in a fixed order", async () => {
    const files = await entries();
    const raw = files.get("tour.json");
    expect(raw).toBeDefined();
    const manifest = parseTourManifest(
      JSON.parse(new TextDecoder().decode(raw)) as unknown,
    );
    expect(manifest.order).toBe("fixed");
    expect(manifest.stations.map((s) => s.id)).toEqual([
      "column",
      "gate",
      "steps",
    ]);
    for (const station of manifest.stations) {
      expect(station.anchor.geo).toBeDefined();
      expect(station.steps.length).toBeGreaterThan(0);
    }
  });

  it("places its stations 20-40 m apart at Marienplatz, so each can be found on its own", async () => {
    const files = await entries();
    const manifest = parseTourManifest(
      JSON.parse(new TextDecoder().decode(files.get("tour.json"))) as unknown,
    );
    const geos = manifest.stations.map((s) => s.anchor.geo!);
    // The column of Marienplatz, Munich (a public place, S-D9).
    expect(metres(geos[0]!, { lat: 48.137393, lon: 11.575493 })).toBeLessThan(
      1,
    );
    for (let i = 0; i < geos.length; i += 1) {
      for (let j = i + 1; j < geos.length; j += 1) {
        const d = metres(geos[i]!, geos[j]!);
        // Apart by more than two found radii (5 m floor), close enough to walk.
        expect(d).toBeGreaterThan(20);
        expect(d).toBeLessThan(40);
      }
    }
  });

  it("carries every asset it names, each allowed, capped and inert", async () => {
    const files = await entries();
    const manifest = parseTourManifest(
      JSON.parse(new TextDecoder().decode(files.get("tour.json"))) as unknown,
    );
    for (const asset of manifest.assets) {
      const bytes = files.get(asset.path);
      expect(bytes, asset.path).toBeDefined();
      expect(tourMediaTypeOfEntry(asset.path), asset.path).not.toBeNull();
    }
    expect(checkImageWithinCap(files.get("content/knight.png")!)).toEqual({
      ok: true,
    });
    expect(checkGlbInert(files.get("content/arch.glb")!)).toEqual({ ok: true });
  });

  it("stores its entries uncompressed, so a visitor can stream them", async () => {
    const reader = new ZipReader(new BlobReader(new Blob([readFileSync(ZIP)])));
    const list = await reader.getEntries();
    await reader.close();
    for (const entry of list) {
      expect(entry.compressedSize, entry.filename).toBe(entry.uncompressedSize);
    }
    // TextWriter keeps the import honest for a text entry read.
    expect(TextWriter).toBeDefined();
  });
});
